# GitHub Actions 配置文件的名字
name: Build Cherry Studio for Windows

# 触发条件：当手动点击 "Run workflow" 按钮时运行
on:
  workflow_dispatch:

jobs:
  build:
    # 指定运行环境：使用 GitHub 提供的最新版 Windows 虚拟机
    runs-on: windows-latest

    steps:
      # 第1步：获取代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'CherryHQ/cherry-studio'
          ref: 'build/windows7-support'

      # 第2步：设置 Node.js 环境并缓存依赖
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn' # 为 yarn 自动设置缓存

      # 第3步：安装 Node.js 依赖
      - name: Install dependencies with Yarn
        run: yarn install --immutable

      # 第4步：安装 Rust 环境并缓存 Cargo 依赖
      - name: Setup Rust and Cache Cargo
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # 第5步：打包 Tauri 应用
      # 【关键修改】明确指定只打包 nsis (.exe) 类型，避免 WiX 工具的权限问题
      - name: Build the application
        run: yarn tauri build --bundles "nsis"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 第6步：上传打包好的文件
      # 【关键修改】只上传存在的 .exe 文件
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cherry-studio-windows-installer
          path: src-tauri/target/release/bundle/nsis/*.exe
