name: Build Cherry Studio for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'CherryHQ/cherry-studio'
          ref: 'build/windows7-support'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies with Yarn
        run: yarn install --immutable

      # 安装 tauri CLI 和 Rust 环境
      - name: Install Tauri CLI
        run: yarn add @tauri-apps/cli --dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # 构建只打包 NSIS .exe
      - name: Build the application (.exe only)
        run: yarn tauri build --bundles nsis
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # 上传打好的 exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cherry-studio-windows-installer
          path: src-tauri/target/release/bundle/nsis/*.exe
